#!/bin/sh
# Generates SyncScope's launcher icons from one high-resolution image
# (feature 007, research R17, FR-018).
#
#   scripts/icon/generate-icons.sh <source.png> [--background '#RRGGBB']
#                                  [--res <dir>] [--assets <dir>]
#
#   --background  the adaptive icon's background colour (default #FFFFFF)
#   --res         the Android res directory (default android/app/src/main/res)
#   --assets      where the store image and the source go (default assets/icon)
#
# Writes, into --res:
#   mipmap-anydpi/ic_launcher.xml, ic_launcher_round.xml   adaptive icons with
#       a background colour, a foreground and a monochrome (themed) layer
#   values/ic_launcher_background.xml                      the background colour
#   mipmap-<density>/ic_launcher_foreground.png            108 dp, the image
#       scaled into the central 66 dp safe zone
#   mipmap-<density>/ic_launcher_monochrome.png            108 dp, the
#       foreground's alpha filled white
#   mipmap-<density>/ic_launcher.png, ic_launcher_round.png  48 dp legacy icons
# and, into --assets: play-store-512.png and source.png (a copy of the input,
# so the icons can be regenerated).
#
# Needs ImageMagick 7 (`magick`); only this script uses it, never the build.
set -eu

usage() {
  echo "usage: $0 <source.png> [--background '#RRGGBB'] [--res <dir>] [--assets <dir>]" >&2
  exit 64
}

fail() {
  echo "generate-icons: $*" >&2
  exit 1
}

if ! command -v magick >/dev/null 2>&1; then
  fail "ImageMagick 7 is required: the 'magick' command was not found on PATH (see DEVELOPMENT.md)"
fi

repo=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
source=
background='#FFFFFF'
res="$repo/android/app/src/main/res"
assets="$repo/assets/icon"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --background) [ "$#" -ge 2 ] || usage; background=$2; shift 2 ;;
    --res) [ "$#" -ge 2 ] || usage; res=$2; shift 2 ;;
    --assets) [ "$#" -ge 2 ] || usage; assets=$2; shift 2 ;;
    -*) usage ;;
    *) [ -z "$source" ] || usage; source=$1; shift ;;
  esac
done

[ -n "$source" ] || usage
[ -f "$source" ] || fail "source image not found: $source"
case "$background" in
  '#'[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]) ;;
  *) fail "--background must be #RRGGBB, got: $background" ;;
esac

size=$(magick "$source[0]" -format '%w %h' info:) || fail "cannot read $source"
width=${size% *}
height=${size#* }
if [ "$width" -lt 512 ] || [ "$height" -lt 512 ]; then
  fail "source image is ${width}x${height}; it must be at least 512x512"
fi

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT INT TERM

# The source fitted into the 66 dp safe zone of a 108 dp layer, at the given
# safe-zone and layer sizes in px. Each density is rendered from the source,
# so resampling never spreads the image outside its safe zone.
foreground() {
  magick "$source[0]" -background none -alpha set \
    -resize "${1}x${1}" -gravity center -extent "${2}x${2}" "png32:$3"
}

# The monochrome (themed icon) layer: the foreground's alpha, filled white.
monochrome() {
  magick "$1" -alpha extract -background white -alpha shape "png32:$2"
}

# The legacy and store icons start from the full icon at 4x (432 px).
foreground 264 432 "$work/foreground.png"
# The full icon as a launcher shows it: the foreground over the background.
magick -size 432x432 "xc:$background" "$work/foreground.png" \
  -compose over -composite "png32:$work/full.png"
# Legacy icons show the adaptive icon's 72 dp viewport (288 px at 4x).
magick "$work/full.png" -gravity center -crop 288x288+0+0 +repage \
  "png32:$work/legacy.png"
magick "$work/legacy.png" \
  \( -size 288x288 xc:black -fill white -draw 'circle 143.5,143.5 143.5,0' \) \
  -alpha off -compose copy_opacity -composite "png32:$work/legacy-round.png"

for entry in mdpi:1 hdpi:1.5 xhdpi:2 xxhdpi:3 xxxhdpi:4; do
  density=${entry%%:*}
  scale=${entry#*:}
  layer=$(awk "BEGIN { print 108 * $scale }")
  zone=$(awk "BEGIN { print 66 * $scale }")
  legacy=$(awk "BEGIN { print 48 * $scale }")
  dir="$res/mipmap-$density"
  mkdir -p "$dir"
  foreground "$zone" "$layer" "$dir/ic_launcher_foreground.png"
  monochrome "$dir/ic_launcher_foreground.png" "$dir/ic_launcher_monochrome.png"
  magick "$work/legacy.png" -filter Lanczos -resize "${legacy}x${legacy}!" \
    "png32:$dir/ic_launcher.png"
  magick "$work/legacy-round.png" -filter Lanczos -resize "${legacy}x${legacy}!" \
    "png32:$dir/ic_launcher_round.png"
done

mkdir -p "$res/mipmap-anydpi" "$res/values"
for name in ic_launcher ic_launcher_round; do
  cat >"$res/mipmap-anydpi/$name.xml" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/icon/generate-icons.sh; do not edit. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />
</adaptive-icon>
XML
done
cat >"$res/values/ic_launcher_background.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/icon/generate-icons.sh; do not edit. -->
<resources>
    <color name="ic_launcher_background">$background</color>
</resources>
XML

mkdir -p "$assets"
magick "$work/full.png" -filter Lanczos -resize 512x512! "png32:$assets/play-store-512.png"
if ! [ "$source" -ef "$assets/source.png" ]; then
  cp "$source" "$assets/source.png"
fi

echo "generate-icons: wrote the launcher icons to $res and the store image to $assets"
