package com.syncscope.persistence

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Guards the exported Room schema (generated by KSP into `schemas/`):
 * repository rows must never contain password or recoverable secret columns,
 * and the match/paging indexes the matcher and browsers rely on must exist.
 */
class SchemaContractTest {

  /** The current schema version's export; older exports stay frozen for MigrationTest. */
  private val schemaFile = schemaExport(5)

  private fun schemaExport(version: Int) =
    File("schemas/com.syncscope.persistence.SyncScopeDatabase/$version.json")

  private val schemaText: String by lazy {
    assertTrue("exported Room schema must exist", schemaFile.isFile)
    schemaFile.readText()
  }

  @Test
  fun repositoryConfigContainsNoCredentialMaterial() {
    val configSection = sectionFor("repository_config")
    val forbidden =
      listOf("password", "secret", "ciphertext", "cipher", "nonce", "credential_blob", "token")
    for (column in forbidden) {
      assertFalse(
        "repository_config must not contain a '$column' column",
        configSection.contains("\"$column\"", ignoreCase = true) ||
          configSection.contains("\"fieldPath\": \"$column", ignoreCase = true),
      )
    }
    // The versioned credential reference is allowed; it is not a secret.
    assertTrue(configSection.contains("credentialVersion"))
  }

  @Test
  fun sourceAndRunTablesContainNoCredentialMaterial() {
    for (table in listOf("source_root", "scan_run", "snapshot", "active_snapshot")) {
      val section = sectionFor(table)
      assertFalse("$table must not contain password columns", section.contains("password", ignoreCase = true))
      assertFalse("$table must not contain secret columns", section.contains("secret", ignoreCase = true))
      assertFalse("$table must not contain ciphertext columns", section.contains("ciphertext", ignoreCase = true))
      assertFalse("$table must not contain nonce columns", section.contains("nonce", ignoreCase = true))
    }
  }

  @Test
  fun matchIndexesExist() {
    // Collapsed remote match keys: exact lookup pair and unique full key.
    assertTrue(schemaText.contains("index_remote_match_key_snapshotId_name_sizeBytes"))
    assertTrue(schemaText.contains("index_remote_match_key_snapshotId_name_sizeBytes_precisionMillis_bucket"))
    // Local candidate lookup by name/size.
    assertTrue(schemaText.contains("index_local_node_snapshotId_name_sizeBytes"))
  }

  @Test
  fun pagingAndViewIndexesExist() {
    assertTrue(schemaText.contains("index_local_node_snapshotId_status_name"))
    assertTrue(schemaText.contains("index_local_node_snapshotId_sourceId_parentId_kind_name"))
    assertTrue(schemaText.contains("index_local_node_snapshotId_kind_modifiedUtcMillis"))
    assertTrue(schemaText.contains("index_local_deletion_overlay_snapshotId_localEntryId"))
  }

  @Test
  fun uniqueKeysExist() {
    assertTrue(schemaText.contains("index_trusted_sftp_host_key_host_port_algorithm"))
    assertTrue(schemaText.contains("index_source_root_canonicalRoot"))
    assertTrue(schemaText.contains("index_scan_run_generation"))
    assertTrue(schemaText.contains("index_snapshot_scanRunId"))
  }

  @Test
  fun version2ColumnsAreDeclared() {
    val scanRun = sectionFor("scan_run")
    assertTrue(scanRun.contains("`mode` TEXT NOT NULL DEFAULT 'FULL'"))
    val snapshot = sectionFor("snapshot")
    assertTrue(snapshot.contains("`remoteListedAtMillis` INTEGER,"))
    assertFalse(snapshot.contains("`remoteListedAtMillis` INTEGER NOT NULL"))
  }

  @Test
  fun version3DescendantCountColumnsAreNullableIntegers() {
    val localNode = sectionFor("local_node")
    for (column in listOf("descSynced", "descUnsynced", "descUnknown")) {
      assertTrue(
        "$column must be a nullable INTEGER",
        localNode.contains("`$column` INTEGER,") || localNode.contains("`$column` INTEGER)"),
      )
      assertFalse("$column must be nullable", localNode.contains("`$column` INTEGER NOT NULL"))
    }
  }

  @Test
  fun version3AddsNoIndex() {
    assertEquals(indexNames(2), indexNames(3))
  }

  @Test
  fun version4AddsNullableDirectoriesAndWebdavHttpsDefaultingToFalse() {
    val matchKey = sectionFor("remote_match_key")
    assertTrue(
      "remote_match_key.directories must be a nullable TEXT",
      matchKey.contains("`directories` TEXT,") || matchKey.contains("`directories` TEXT)"),
    )
    assertFalse(matchKey.contains("`directories` TEXT NOT NULL"))
    assertTrue(
      "repository_config.webdavHttps must be a NOT NULL INTEGER defaulting to 0",
      sectionFor("repository_config").contains("`webdavHttps` INTEGER NOT NULL DEFAULT 0"),
    )
  }

  @Test
  fun version4AddsNoIndex() {
    assertEquals(indexNames(3), indexNames(4))
  }

  @Test
  fun version5RenamesRemoteRootsAndAddsSortNameRemotePathAndTwoIndexes() {
    assertTrue(schemaText.contains("\"version\": 5"))
    val repository = sectionFor("repository_config")
    assertTrue(repository.contains("`remoteRoots` TEXT NOT NULL"))
    assertFalse(repository.contains("`remoteRoot` TEXT"))
    assertTrue(
      "local_node.sortName must be a NOT NULL TEXT defaulting to ''",
      sectionFor("local_node").contains("`sortName` TEXT NOT NULL DEFAULT ''"),
    )
    val ambiguity = sectionFor("remote_ambiguity")
    assertTrue(
      "remote_ambiguity.remotePath must be a nullable TEXT",
      ambiguity.contains("`remotePath` TEXT,") || ambiguity.contains("`remotePath` TEXT)"),
    )
    assertFalse(ambiguity.contains("`remotePath` TEXT NOT NULL"))
    assertEquals(
      indexNames(4) + setOf("index_local_node_snapshotId_kind_sizeBytes", "index_local_node_snapshotId_kind_sortName"),
      indexNames(5),
    )
  }

  @Test
  fun repositoryConfigColumnsAreExactlyTheNonSecretOnes() {
    // A new column must be added here deliberately, after checking it carries no secret.
    val fields =
      Regex("\"columnName\": \"(\\w+)\"").findAll(sectionFor("repository_config")).map { it.groupValues[1] }.toList()
    assertEquals(
      listOf(
        "id", "protocol", "host", "port", "username", "remoteRoots", "precisionMillis", "credentialVersion",
        "revision", "webdavHttps",
      ),
      fields,
    )
  }

  @Test
  fun foreignKeysAreDeclared() {
    val localNode = sectionFor("local_node")
    assertTrue(localNode.contains("\"table\": \"snapshot\""))
    assertTrue(localNode.contains("\"table\": \"source_root\""))
    assertTrue(sectionFor("snapshot").contains("\"table\": \"scan_run\""))
  }

  private fun indexNames(version: Int): Set<String> {
    val file = schemaExport(version)
    assertTrue("exported schema $version must exist", file.isFile)
    return Regex("\"name\": \"(index_[A-Za-z0-9_]+)\"").findAll(file.readText()).map { it.groupValues[1] }.toSet()
  }

  private fun sectionFor(tableName: String): String {
    val marker = "\"tableName\": \"$tableName\""
    val start = schemaText.indexOf(marker)
    assertTrue("schema must contain $tableName", start >= 0)
    val next = schemaText.indexOf("\"tableName\":", start + marker.length)
    return if (next >= 0) schemaText.substring(start, next) else schemaText.substring(start)
  }
}
