package com.syncscope.persistence

import java.io.File
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Guards the exported Room schema (generated by KSP into `schemas/`):
 * repository rows must never contain password or recoverable secret columns,
 * and the match/paging indexes the matcher and browsers rely on must exist.
 */
class SchemaContractTest {

  private val schemaFile =
    File("schemas/com.syncscope.persistence.SyncScopeDatabase/1.json")

  private val schemaText: String by lazy {
    assertTrue("exported Room schema must exist", schemaFile.isFile)
    schemaFile.readText()
  }

  @Test
  fun repositoryConfigContainsNoCredentialMaterial() {
    val configSection = sectionFor("repository_config")
    val forbidden =
      listOf("password", "secret", "ciphertext", "cipher", "nonce", "credential_blob", "token")
    for (column in forbidden) {
      assertFalse(
        "repository_config must not contain a '$column' column",
        configSection.contains("\"$column\"", ignoreCase = true) ||
          configSection.contains("\"fieldPath\": \"$column", ignoreCase = true),
      )
    }
    // The versioned credential reference is allowed; it is not a secret.
    assertTrue(configSection.contains("credentialVersion"))
  }

  @Test
  fun sourceAndRunTablesContainNoCredentialMaterial() {
    for (table in listOf("source_root", "scan_run", "snapshot", "active_snapshot")) {
      val section = sectionFor(table)
      assertFalse("$table must not contain password columns", section.contains("password", ignoreCase = true))
      assertFalse("$table must not contain secret columns", section.contains("secret", ignoreCase = true))
      assertFalse("$table must not contain ciphertext columns", section.contains("ciphertext", ignoreCase = true))
      assertFalse("$table must not contain nonce columns", section.contains("nonce", ignoreCase = true))
    }
  }

  @Test
  fun matchIndexesExist() {
    // Collapsed remote match keys: exact lookup pair and unique full key.
    assertTrue(schemaText.contains("index_remote_match_key_snapshotId_name_sizeBytes"))
    assertTrue(schemaText.contains("index_remote_match_key_snapshotId_name_sizeBytes_precisionMillis_bucket"))
    // Local candidate lookup by name/size.
    assertTrue(schemaText.contains("index_local_node_snapshotId_name_sizeBytes"))
  }

  @Test
  fun pagingAndViewIndexesExist() {
    assertTrue(schemaText.contains("index_local_node_snapshotId_status_name"))
    assertTrue(schemaText.contains("index_local_node_snapshotId_sourceId_parentId_kind_name"))
    assertTrue(schemaText.contains("index_local_node_snapshotId_kind_modifiedUtcMillis"))
    assertTrue(schemaText.contains("index_local_deletion_overlay_snapshotId_localEntryId"))
  }

  @Test
  fun uniqueKeysExist() {
    assertTrue(schemaText.contains("index_trusted_sftp_host_key_host_port_algorithm"))
    assertTrue(schemaText.contains("index_source_root_canonicalRoot"))
    assertTrue(schemaText.contains("index_scan_run_generation"))
    assertTrue(schemaText.contains("index_snapshot_scanRunId"))
  }

  @Test
  fun foreignKeysAreDeclared() {
    val localNode = sectionFor("local_node")
    assertTrue(localNode.contains("\"referenceTable\": \"snapshot\""))
    assertTrue(localNode.contains("\"referenceTable\": \"source_root\""))
    assertTrue(sectionFor("snapshot").contains("\"referenceTable\": \"scan_run\""))
  }

  private fun sectionFor(tableName: String): String {
    val marker = "\"tableName\": \"$tableName\""
    val start = schemaText.indexOf(marker)
    assertTrue("schema must contain $tableName", start >= 0)
    val next = schemaText.indexOf("\"tableName\":", start + marker.length)
    return if (next >= 0) schemaText.substring(start, next) else schemaText.substring(start)
  }
}
