listen=YES
listen_ipv6=NO
background=NO
anonymous_enable=NO
local_enable=YES
write_enable=NO
chroot_local_user=YES
allow_writeable_chroot=NO
pasv_enable=YES
pasv_min_port=32200
pasv_max_port=32209
pasv_address=10.0.2.2
utf8_filesystem=YES
use_localtime=NO
seccomp_sandbox=NO
syslog_enable=NO
log_ftp_protocol=YES
xferlog_enable=YES
vsftpd_log_file=/var/log/syncscope/vsftpd.log
